kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 9092
      nodePort: 30085
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-service
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          image: test/hello-service
          imagePullPolicy: Never
          ports:
            - containerPort: 9092